# Generated by Django 3.0.5 on 2020-05-01 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20200501_0110'),
        ('reg_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
            preserve_default=False,
        ),
    ]
