# Generated by Django 2.1.5 on 2020-05-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_hora_extra', '0002_horaextra_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
