# Generated by Django 2.1.5 on 2020-05-06 18:00

import apps.documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_auto_20200505_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to=apps.documentos.models.user_directory_path),
        ),
    ]
